//go:build linux

package tun

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

var linuxResolvConfPath = "/etc/resolv.conf"

func overrideSystemDNS(serverIP, iface string) (*systemDNSOverride, error) {
	if iface == "" {
		return nil, fmt.Errorf("missing tun interface name")
	}
	if _, err := exec.LookPath("resolvectl"); err != nil {
		if !errors.Is(err, exec.ErrNotFound) {
			return nil, fmt.Errorf("look up resolvectl: %w", err)
		}
		states, err := linuxCurrentResolvConfDNS()
		if err != nil {
			return nil, err
		}
		if err := linuxApplyResolvConfDNSOverride(states, serverIP); err != nil {
			return nil, err
		}
		return newSystemDNSOverride(serverIP, states, func() ([]systemDNSState, error) {
			return linuxCurrentResolvConfDNS()
		}, linuxApplyResolvConfDNSOverride, linuxRestoreResolvConfDNS), nil
	}

	states, err := currentSystemDNS(iface)
	if err != nil {
		return nil, err
	}
	if len(states) == 0 {
		states = []systemDNSState{{Name: iface, Empty: true}}
	}
	if err := linuxApplyDNSOverride(states, serverIP); err != nil {
		return nil, err
	}

	return newSystemDNSOverride(serverIP, states, func() ([]systemDNSState, error) {
		return currentSystemDNS(iface)
	}, linuxApplyDNSOverride, linuxRestoreDNS), nil
}

func currentSystemDNS(iface string) ([]systemDNSState, error) {
	if iface == "" {
		return nil, nil
	}
	if _, err := exec.LookPath("resolvectl"); err != nil {
		if !errors.Is(err, exec.ErrNotFound) {
			return nil, fmt.Errorf("look up resolvectl: %w", err)
		}
		return linuxCurrentResolvConfDNS()
	}
	out, err := exec.Command("resolvectl", "dns", iface).CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("resolvectl dns %s: %s: %w", iface, strings.TrimSpace(string(out)), err)
	}
	text := strings.TrimSpace(string(out))
	if text == "" {
		return []systemDNSState{{Name: iface, Empty: true}}, nil
	}
	var servers []string
	for _, line := range strings.Split(text, "\n") {
		if _, rest, ok := strings.Cut(line, ":"); ok {
			for _, field := range strings.Fields(rest) {
				servers = append(servers, field)
			}
		}
	}
	return []systemDNSState{{Name: iface, Servers: servers, Empty: len(servers) == 0}}, nil
}

func linuxApplyDNSOverride(states []systemDNSState, serverIP string) error {
	for _, state := range states {
		if state.Name == "" {
			continue
		}
		if err := linuxSetPunchDNS(state.Name, serverIP); err != nil {
			return err
		}
	}
	return nil
}

func linuxSetPunchDNS(iface, serverIP string) error {
	steps := [][]string{
		{"dns", iface, serverIP},
		{"domain", iface, "~."},
		{"default-route", iface, "yes"},
	}
	for _, args := range steps {
		if out, err := exec.Command("resolvectl", args...).CombinedOutput(); err != nil {
			return fmt.Errorf("resolvectl %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(string(out)), err)
		}
	}
	return nil
}

func linuxRestoreDNS(states []systemDNSState) error {
	var firstErr error
	for _, state := range states {
		if state.Name == "" {
			continue
		}
		if state.Empty || len(state.Servers) == 0 {
			if out, err := exec.Command("resolvectl", "revert", state.Name).CombinedOutput(); err != nil && firstErr == nil {
				firstErr = fmt.Errorf("resolvectl revert %s: %s: %w", state.Name, strings.TrimSpace(string(out)), err)
			}
			continue
		}
		args := append([]string{"dns", state.Name}, state.Servers...)
		if out, err := exec.Command("resolvectl", args...).CombinedOutput(); err != nil && firstErr == nil {
			firstErr = fmt.Errorf("resolvectl %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(string(out)), err)
		}
	}
	return firstErr
}

func linuxCurrentResolvConfDNS() ([]systemDNSState, error) {
	content, err := os.ReadFile(linuxResolvConfPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", linuxResolvConfPath, err)
	}
	servers := linuxParseResolvConfNameservers(string(content))
	return []systemDNSState{{
		Name:    linuxResolvConfPath,
		Servers: servers,
		Empty:   len(servers) == 0,
		Content: string(content),
	}}, nil
}

func linuxApplyResolvConfDNSOverride(states []systemDNSState, serverIP string) error {
	content := "# Generated by Punch. Original resolv.conf will be restored when Punch stops.\n" +
		"nameserver " + serverIP + "\n"
	if err := os.WriteFile(linuxResolvConfPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", linuxResolvConfPath, err)
	}
	return nil
}

func linuxRestoreResolvConfDNS(states []systemDNSState) error {
	content := ""
	for _, state := range states {
		if state.Name == linuxResolvConfPath {
			content = state.Content
			break
		}
	}
	if err := os.WriteFile(linuxResolvConfPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("restore %s: %w", linuxResolvConfPath, err)
	}
	return nil
}

func linuxParseResolvConfNameservers(content string) []string {
	var servers []string
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "nameserver" {
			servers = append(servers, fields[1])
		}
	}
	return servers
}
